continuation_prompt = ' ' # Codicons, Add, EA60
continuation_prompt = ' ' # Codicons, Debug Continue, EACF
continuation_prompt = ' ' # Codicons, Debug Continue Small, EBE0
continuation_prompt = ' ' # Codicons, Arrow Circle Right, EBFA
continuation_prompt = ' ' # Codicons, Export, EBAC
continuation_prompt = ' ' # Codicons, Indent, EBF9
continuation_prompt = ' ' # Codicons, Run All, EB9E
continuation_prompt = ' ' # Codicons, Triangle Right, EB70
continuation_prompt = ' ' # Custom, Chuck, E6B6
continuation_prompt = ' ' # Custom, Play Arrow, E602
continuation_prompt = ' ' # Font Awesome, Angle Double Right, F101
continuation_prompt = ' ' # Font Awesome, Angles Right, F101
continuation_prompt = ' ' # Font Awesome, Arrow Circle O Right, F18E
continuation_prompt = ' ' # Font Awesome, Arrow Circle Right, F0A9
continuation_prompt = ' ' # Font Awesome, Arrow Right, F061
continuation_prompt = ' ' # Font Awesome, Arrow Right From Bracket, F08B
continuation_prompt = ' ' # Font Awesome, Arrow Right Long, F178
continuation_prompt = ' ' # Font Awesome, Caret Right, F0DA
continuation_prompt = ' ' # Font Awesome, Circle Arrow Right, F0A9
continuation_prompt = ' ' # Font Awesome, Chevron Circle Right, F138
continuation_prompt = ' ' # Font Awesome, Circle Chevron Right, F138
continuation_prompt = ' ' # Font Awesome, Circle Play, F144
continuation_prompt = ' ' # Font Awesome, Ellipsis, F141
continuation_prompt = ' ' # Font Awesome, Ellipsis H, F141
continuation_prompt = ' ' # Font Awesome, Forward, F04E
continuation_prompt = ' ' # Font Awesome, Greater Than, EDFB
continuation_prompt = ' ' # Font Awesome, Greater Than Equal, EDFC
continuation_prompt = ' ' # Font Awesome, Hand O Right, F0A4
continuation_prompt = ' ' # Font Awesome, Hand Point Right, F0A4
continuation_prompt = ' ' # Font Awesome, Right From Bracket, F2F5
continuation_prompt = ' ' # Font Awesome, Sign Out, F08B
continuation_prompt = ' ' # Font Awesome Extension, Bigger, E285
continuation_prompt = ' ' # Font Awesome Extension, Equal Bigger, E27A
continuation_prompt = '󰞘 ' # Material Design Icons, Arrow Expand Right, F0798
continuation_prompt = '󰁔 ' # Material Design Icons, Arrow Right, F0054
continuation_prompt = '󰜴 ' # Material Design Icons, Arrow Right Bold, F0734
continuation_prompt = '󰜵 ' # Material Design Icons, Arrow Right Bold Box, F0735
continuation_prompt = '󰜶 ' # Material Design Icons, Arrow Right Bold Box Outline, F0736
continuation_prompt = '󰁖 ' # Material Design Icons, Arrow Right Bold Circle, F0056
continuation_prompt = '󰁗 ' # Material Design Icons, Arrow Right Bold Circle Outline, F0057
continuation_prompt = '󰧂 ' # Material Design Icons, Arrow Right Bold Outline, F09C2
continuation_prompt = '󱞩 ' # Material Design Icons, Arrow Right Bottom, F17A9
continuation_prompt = '󱞪 ' # Material Design Icons, Arrow Right Bottom Bold, F17AA
continuation_prompt = '󰛂 ' # Material Design Icons, Arrow Right Box, F06C2
continuation_prompt = '󰳟 ' # Material Design Icons, Arrow Right Circle, F0CDF
continuation_prompt = '󰳠 ' # Material Design Icons, Arrow Right Circle Outline, F0CE0
continuation_prompt = '󰁙 ' # Material Design Icons, Arrow Right Drop Circle, F0059
continuation_prompt = '󰁚 ' # Material Design Icons, Arrow Right Drop Circle Outline, F005A
continuation_prompt = '󰁕 ' # Material Design Icons, Arrow Right Thick, F0055
continuation_prompt = '󱦰 ' # Material Design Icons, Arrow Right Thin, F19B0
continuation_prompt = '󱖘 ' # Material Design Icons, Arrow Right Thin Circle Outline, F1598
continuation_prompt = '󱞵 ' # Material Design Icons, Arrow U Right Bottom, F17B5
continuation_prompt = '󱞶 ' # Material Design Icons, Arrow U Right Bottom, F17B6
continuation_prompt = '󰄾 ' # Material Design Icons, Chevron Double Right, F013E
continuation_prompt = '󰅂 ' # Material Design Icons, Chevron Right, F0142
continuation_prompt = '󰧚 ' # Material Design Icons, Chevron Right Box, F09DA
continuation_prompt = '󰧛 ' # Material Design Icons, Chevron Right Box Outline, F09DB
continuation_prompt = '󰬪 ' # Material Design Icons, Chevron Right Circle, F0B2A
continuation_prompt = '󰬫 ' # Material Design Icons, Chevron Right Circle Outline, F0B2B
continuation_prompt = '󰶻 ' # Material Design Icons, Chevron Triple Right, F0DBB
continuation_prompt = '󰊍 ' # Material Design Icons, Forward, F028D
continuation_prompt = '󰵵 ' # Material Design Icons, Forwardburger, F0D75
continuation_prompt = '󰣡 ' # Material Design Icons, Gate And, F08E1
continuation_prompt = '󰥭 ' # Material Design Icons, Greater Than, F096D
continuation_prompt = '󰋇 ' # Material Design Icons, Hand Pointing Right, F02C7
continuation_prompt = '󰿅 ' # Material Design Icons, Location Exit, F0FC5
continuation_prompt = '󰍃 ' # Material Design Icons, Logout, F0342
continuation_prompt = '󰗽 ' # Material Design Icons, Logout Variant, F05FD
continuation_prompt = '󰽝 ' # Material Design Icons, Middleware, F0F5D
continuation_prompt = '󰽞 ' # Material Design Icons, Middleware Outline, F0F5E
continuation_prompt = '󰮺 ' # Material Design Icons, Pan Right, F0BBA
continuation_prompt = '󰐊 ' # Material Design Icons, Play, F040A
continuation_prompt = '󱉺 ' # Material Design Icons, Play Box, F127A
continuation_prompt = '󰐋 ' # Material Design Icons, Play Box Outline, F040B
continuation_prompt = '󰐌 ' # Material Design Icons, Play Circle, F040C
continuation_prompt = '󰐍 ' # Material Design Icons, Play Circle Outline, F040D
continuation_prompt = '󰼛 ' # Material Design Icons, Play Outline, F0F1B
continuation_prompt = '󰚺 ' # Material Design Icons, Plex, F06BA
continuation_prompt = '󰐕 ' # Material Design Icons, Plus, F0415
continuation_prompt = '󰐖 ' # Material Design Icons, Plus Box, F0416
continuation_prompt = '󰜄 ' # Material Design Icons, Plus Box Outline, F0704
continuation_prompt = '󰐗 ' # Material Design Icons, Plus Circle, F0417
continuation_prompt = '󰐙 ' # Material Design Icons, Plus Circle Outline, F0419
continuation_prompt = '󰜅 ' # Material Design Icons, Plus Outline, F0705
continuation_prompt = '󱇬 ' # Material Design Icons, Plus Thick, F11EC
continuation_prompt = '󰳀 ' # Material Design Icons, Radius, F0CC0
continuation_prompt = '󰳁 ' # Material Design Icons, Radius Outline, F0CC1
continuation_prompt = '󰑃 ' # Material Design Icons, Ray Start Arrow, F0443
continuation_prompt = '󰑎 ' # Material Design Icons, Redo, F044E
continuation_prompt = '󱜧 ' # Material Design Icons, Script Text Play, F1727
continuation_prompt = '󱜨 ' # Material Design Icons, Script Text Play Outline, F1728
continuation_prompt = '󰒊 ' # Material Design Icons, Send, F048A
continuation_prompt = '󰷸 ' # Material Design Icons, Send Circle, F0DF8
continuation_prompt = '󰷹 ' # Material Design Icons, Send Circle, F0DF9
continuation_prompt = '󱅥 ' # Material Design Icons, Send Outline, F1165
continuation_prompt = '󱓡 ' # Material Design Icons, Set Split, F14E1
continuation_prompt = '󰒞 ' # Material Design Icons, Shuffle Disabled, F049E
continuation_prompt = '󰘍 ' # Material Design Icons, Subdirectory Arrow Right, F060D
continuation_prompt = '󰔰 ' # Material Design Icons, Transfer Right, F0530
continuation_prompt = '󰔴 ' # Material Design Icons, Trending Neutral, F0534
continuation_prompt = '󰔾 ' # Material Design Icons, Truck Delivery, F053E
continuation_prompt = '󱊛 ' # Material Design Icons, Truck Delivery Outline, F129B
continuation_prompt = '󱡚 ' # Material Design Icons, Waves Arrow Right, F185A
continuation_prompt = '󰯟 ' # Material Design Icons, Wrap Disabled, F0BDF
continuation_prompt = ' ' # Octicons, Arrow Right, F432
continuation_prompt = ' ' # Octicons, Chevron Right, F460
continuation_prompt = ' ' # Octicons, Diff Renamed, F45A
continuation_prompt = ' ' # Octicons, Iterations, F4EA
continuation_prompt = ' ' # Octicons, Package Dependents, F4F9
continuation_prompt = ' ' # Octicons, Paper Airplane, F4FA
continuation_prompt = ' ' # Octicons, Play, F500
continuation_prompt = ' ' # Octicons, Plus, F44D
continuation_prompt = ' ' # Octicons, Plus Circle, F501
continuation_prompt = ' ' # Octicons, Sign Out, F426
continuation_prompt = ' ' # Weather Icons, Direction Right, E349
continuation_prompt = ' ' # Weather Icons, Wind West, E354
