fun_glyph = ' ' # Codicons, Issues, EB0C
fun_glyph = ' ' # Codicons, Record, EBA7
fun_glyph = ' ' # Codicons, Record Small, EBFA
fun_glyph = ' ' # Codicons, Sparkle, EC10
fun_glyph = ' ' # Codicons, Star Full, EB59
fun_glyph = ' ' # Custom, Scheme, E6B1
fun_glyph = ' ' # Font Awesome, Bong, EE25
fun_glyph = ' ' # Font Awesome, Brain, EE9C
fun_glyph = ' ' # Font Awesome, Circle Dot, f192
fun_glyph = ' ' # Font Awesome, Dot Circle O, f192
fun_glyph = ' ' # Font Awesome, Drum, ee32
fun_glyph = ' ' # Font Awesome, Splotch, ee83
fun_glyph = ' ' # Font Awesome, Hand Middle Finger, EF83
fun_glyph = ' ' # Font Awesome, Jet Fighter, F0FB
fun_glyph = ' ' # Font Awesome, Joint, EE5E
fun_glyph = ' ' # Font Awesome, Plane, F072
fun_glyph = ' ' # Font Awesome, Space Shuttle, F197
fun_glyph = ' ' # Font Awesome, Skull, EE15
fun_glyph = ' ' # Font Awesome, Skull Crossbones, EF0E 
fun_glyph = ' ' # Font Awesome, Terminal, F120
fun_glyph = ' ' # Font Awesome, Triangle Exclamation, F071
fun_glyph = ' ' # Font Awesome, Wand Sparkles, EF15
fun_glyph = ' ' # Font Awesome Extension, Brain, E28C
fun_glyph = ' ' # Font Awesome Extension, Gps, E248
fun_glyph = '󰢚 ' # Material Design Icons, Alien, F089A
fun_glyph = '󱃋 ' # Material Design Icons, Alien Outline, F10CB
fun_glyph = '󰁨 ' # Material Design Icons, Auto Fix, F0068
fun_glyph = '󰣈 ' # Material Design Icons, Axe, F08C8
fun_glyph = '󱡂 ' # Material Design Icons, Axe Battle, F1842
fun_glyph = '󰭟 ' # Material Design Icons, Bat, F0B5F
fun_glyph = '󰄪 ' # Material Design Icons, Chart Line, F1213
fun_glyph = '󰞷 ' # Material Design Icons, Console Line, F07B7
fun_glyph = '󰙴 ' # Material Design Icons, Creation, F0674
fun_glyph = '󰆣 ' # Material Design Icons, Crosshairs, F01A3
fun_glyph = '󰆤 ' # Material Design Icons, Crosshairs Gps, F01A4
fun_glyph = '󰬯 ' # Material Design Icons, Crystal Ball, F02BF
fun_glyph = '󰊠 ' # Material Design Icons, Ghost, F02A0
fun_glyph = '󱙝 ' # Material Design Icons, Ghost Outline, F165D
fun_glyph = '󰊱 ' # Material Design Icons, Google Circles Communities, F02B1 # Nicholas Roerich Peace Symbol
fun_glyph = '󰘧 ' # Material Design Icons, Lambda, F082D
fun_glyph = '󰷚 ' # Material Design Icons, Mine, F0DDA
fun_glyph = '󰽥 ' # Material Design Icons, Moon Waning Crescent, F0F65
fun_glyph = '󰽧 ' # Material Design Icons, Moon Waxing Crescent, F0F67
fun_glyph = '󱖲 ' # Material Design Icons, Motion, F15B2
fun_glyph = '󱖳 ' # Material Design Icons, Motion Outline, F15B3
fun_glyph = '󰟟 ' # Material Design Icons, Mushroom, F07DF
fun_glyph = '󰟠 ' # Material Design Icons, Mushroom Outline, F07E0
fun_glyph = '󰝴 ' # Material Design Icons, Ninja, F0774
fun_glyph = '󰏅 ' # Material Design Icons, Odnoklassniki, F03C5
fun_glyph = '󰮭 ' # Material Design Icons, One Up, F0BAD
fun_glyph = '󰜃 ' # Material Design Icons, Pistol, F0703
fun_glyph = '󱁘 ' # Material Design Icons, Robber, F1058
fun_glyph = '󰓾 ' # Material Design Icons, Target, F04FE
fun_glyph = '󰦫 ' # Material Design Icons, Toilet, F09AB
fun_glyph = '󱂖 ' # Material Design Icons, Trumpet, F1096
fun_glyph = '󱃄 ' # Material Design Icons, Ufo, F10C4
fun_glyph = '󱃅 ' # Material Design Icons, Ufo Outline, F10C5
fun_glyph = '󰕧 ' # Material Design Icons, Video, F0567
fun_glyph = '󰃽 ' # Material Design Icons, Video Box, F00FD
fun_glyph = '󰤚 ' # Material Design Icons, Video Image, F091A
fun_glyph = '󰯜 ' # Material Design Icons, Video Outline, F0BDC
fun_glyph = '󰖔 ' # Material Design Icons, Weather Night, F0594
fun_glyph = '󰼸 ' # Material Design Icons, Weather Tornado, F0F38
fun_glyph = ' ' # Octicons, Beaker, F499
fun_glyph = ' ' # Octicons, Gear, F423
fun_glyph = ' ' # Octicons, Issue Opened, F41B
fun_glyph = ' ' # Octicons, Rocket, F427
fun_glyph = ' ' # Octicons, Sparkle Fill, F51B
