"$schema" = 'https://starship.rs/config-schema.json'

# 󰻃 - Material Design Icons, Record Circle Outline, F0EC3
#  - Codicons, Circle Large Filled, EBB4
#  - Codicons, Circle Filled, EA71

format = """
[](color_bg1)\
[󰻃  ](bg:color_bg1 fg:color_fg1)\
$os\
$shell\
$username\
[](bg:color_bg2 fg:color_bg1)\
$directory\
[](fg:color_bg2 bg:color_bg3)\
$git_branch\
$git_status\
[](fg:color_bg3)\
$fill\
[](fg:color_bg4)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_bg5 bg:color_bg4)\
$docker_context\
$conda\
[](fg:color_bg6 bg:color_bg5)\
$jobs\
$cmd_duration\
$time\
[ 󰻃 ](bg:color_bg6 fg:color_fg1)\
[ ](fg:color_bg6)\
$line_break\
$character"""

#palette = 'gruvbox_dark'
palette = 'nord'
#palette = 'onedark'

continuation_prompt = '󱞩 ' # Material Design Icons, Arrow Right Bottom, F17A9

[line_break]
disabled = false

[character]
disabled = false
#success_symbol = '[󰣈](bold fg:color_bg3)' # Material Design Icons, Axe, F08C8
#success_symbol = '[󰒊](bold fg:color_bg3)' # Material Design Icons, Send, F048A
#success_symbol = '[󰧂](bold fg:color_bg3)' # Material Design Icons, Arrow Right Bold Outline, F09C2
#success_symbol = '[󰜴](bold fg:color_bg3)' # Material Design Icons, Arrow Right Outline, F0734
#success_symbol = '[](bold fg:color_bg3)' # Font Awesome, Crown, EDEB
#success_symbol = '[](bold fg:color_bg3)' # Font Awesome, Splotch:, EE83
success_symbol = '[](bold fg:color_bg3)' # Font Awesome, Toilet Paper, EF11
error_symbol = '[](bold fg:color_fg3)' # Font Awesome, Hand Middle Finger, EF83

[fill]
symbol = '󰗣' # Material Design Icons, Chart Bubble, F05E3


[os]
disabled = false
style = "bg:color_bg1 fg:color_fg1"

[username]
show_always = true
style_user = "bg:color_bg1 fg:color_fg1"
style_root = "bg:color_bg1 fg:color_fg1"
format = '[ $user ]($style)'

[directory]
style = "fg:color_fg1 bg:color_bg2"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Development" = "󰲋 "
"Movies" = "󰟞"

[git_branch]
symbol = ""
style = "fg:color_fg1 bg:color_bg3"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:color_fg1 bg:color_bg3"
format = '[($all_status$ahead_behind )]($style)'

[jobs]
symbol = ' '
number_threshold = 1
style = 'fg:color_fg3 bg:color_bg6'
format = '[$symbol]($style)'

[cmd_duration]
min_time = 500
style = 'fg:color_fg1 bg:color_bg6'
format = '[$duration]($style)'

[time]
disabled = false
time_format = "%R"
style = "fg:color_fg1 bg:color_bg6"
format = '[  $time ]($style)'


[shell]
disabled = false
bash_indicator = '󰬉'
zsh_indicator = '󰰷'
powershell_indicator = ''
unknown_indicator = '⁇'
style = "bg:color_bg1 fg:color_fg1"
format = '[ $indicator]($style)'

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""


[c]
symbol = " "
style = "bg:color_bg4"
format = '[[ $symbol( $version) ](fg:color_fg1 bg:color_bg4)]($style)'

[conda]
style = "bg:color_bg5"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:color_bg5)]($style)'

[docker_context]
symbol = ""
style = "bg:color_bg5"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg5)]($style)'

[golang]
symbol = ""
style = "bg:color_bg4"
format = '[[ $symbol( $version) ](fg:color_fg1 bg:color_bg4)]($style)'

[haskell]
symbol = ""
style = "bg:color_bg4"
format = '[[ $symbol( $version) ](fg:color_fg1 bg:color_bg4)]($style)'

[java]
symbol = ""
style = "bg:color_bg4"
format = '[[ $symbol( $version) ](fg:color_fg1 bg:color_bg4)]($style)'

[kotlin]
symbol = ""
style = "bg:color_bg4"
format = '[[ $symbol( $version) ](fg:color_fg1 bg:color_bg4)]($style)'

[lua]
symbol = ' '
style = "bg:color_bg4"

[nodejs]
symbol = ""
style = "bg:color_bg4"
format = '[[ $symbol( $version) ](fg:color_fg1 bg:color_bg4)]($style)'

[php]
symbol = ""
style = "bg:color_bg4"
format = '[[ $symbol( $version) ](fg:color_fg1 bg:color_bg4)]($style)'

[python]
symbol = ""
style = "bg:color_bg4"
format = '[[ $symbol( $version) ](fg:color_fg1 bg:color_bg4)]($style)'

[ruby]
style = "bg:color_bg4"
symbol = ' '

[rust]
symbol = ""
style = "bg:color_bg4"
format = '[[ $symbol( $version) ](fg:color_fg1 bg:color_bg4)]($style)'


[palettes]

  [palettes.gruvbox_dark]
  color_bg1 = '#d65d0e' # orange
  color_bg2 = '#d79921' # yellow
  color_bg3 = '#689d6a' # aqua
  color_bg4 = '#458588' # blue
  color_bg5 = '#665c54' # dark_yellow
  color_bg6 = '#3c3836' # dark_red
  color_fg1 = '#fbf1c7' # yellow
  color_fg2 = '#98971a' # green
  color_fg3 = '#cc241d' # red
  color_fg4 = '#b16286' # purple

  [palettes.nord]
  color_bg0 = '#2E3440' # black
  color_bg1 = '#B48EAD' # purple
  color_bg2 = '#5E81AC' # dark_blue
  color_bg3 = '#81A1C1' # blue
  color_bg4 = '#88C0D0' # teal
  color_bg5 = '#434C5E' # gray
  color_bg6 = '#D8DEE9' # white
  color_fg1 = '#ffffff' # white
  color_fg2 = '#BF616A' # red
  color_fg3 = '#D08770' # orange
  color_fg5 = '#EBCB8B' # yellow
  color_fg4 = '#A3BE8C' # green

  [palettes.onedark]
  color_bg0 = '#2c323c' # black
  color_bg1 = '#c678dd' # purple
  color_bg2 = '#61afef' # dark_blue
  color_bg3 = '#56b6c2' # blue
  color_bg4 = '#56b6c2' # cyan
  color_bg5 = '#828997' # gray
  color_bg6 = '#98c379' # green
  #color_fg1 = '#f8fafd' # white
  color_fg1 = '#ffffff' # white
  color_fg2 = '#abb2bf' # light gray
  color_fg3 = '#e06c75' # red
  color_fg4 = '#be5046' # orange
  color_fg5 = '#e5c07b' # yellow
