"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_orange)\
$os\
$shell\
$username\
[](bg:color_yellow fg:color_orange)\
$directory\
[](fg:color_yellow bg:color_aqua)\
$git_branch\
$git_status\
[](fg:color_aqua bg:color_blue)\
$fill\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_blue bg:color_bg3)\
$docker_context\
$conda\
[](fg:color_bg3 bg:color_bg1)\
$jobs\
$cmd_duration\
$time\
[ ](fg:color_bg1)\
$line_break\
$character"""

palette = 'gruvbox_dark'


continuation_prompt = '󱞩 ' # Material Design Icons, Arrow Right Bottom, F17A9
#continuation_prompt = '󰘍 ' # Material Design Icons, Subdirectory Arrow Right, F060D

#continuation_prompt = ' ' # Codicons, Add, EA60
#continuation_prompt = ' ' # Codicons, Debug Continue, EACF
#continuation_prompt = ' ' # Codicons, Debug Continue Small, EBE0
#continuation_prompt = ' ' # Codicons, Arrow Circle Right, EBFA
#continuation_prompt = ' ' # Codicons, Export, EBAC
#continuation_prompt = ' ' # Codicons, Indent, EBF9
#continuation_prompt = ' ' # Codicons, Run All, EB9E
#continuation_prompt = ' ' # Codicons, Triangle Right, EB70
#continuation_prompt = ' ' # Custom, Chuck, E6B6
#continuation_prompt = ' ' # Custom, Play Arrow, E602
#continuation_prompt = ' ' # Font Awesome, Angle Double Right, F101
#continuation_prompt = ' ' # Font Awesome, Angles Right, F101
#continuation_prompt = ' ' # Font Awesome, Arrow Circle O Right, F18E
#continuation_prompt = ' ' # Font Awesome, Arrow Circle Right, F0A9
#continuation_prompt = ' ' # Font Awesome, Arrow Right, F061
#continuation_prompt = ' ' # Font Awesome, Arrow Right From Bracket, F08B
#continuation_prompt = ' ' # Font Awesome, Arrow Right Long, F178
#continuation_prompt = ' ' # Font Awesome, Caret Right, F0DA
#continuation_prompt = ' ' # Font Awesome, Circle Arrow Right, F0A9
#continuation_prompt = ' ' # Font Awesome, Chevron Circle Right, F138
#continuation_prompt = ' ' # Font Awesome, Circle Chevron Right, F138
#continuation_prompt = ' ' # Font Awesome, Circle Play, F144
#continuation_prompt = ' ' # Font Awesome, Ellipsis, F141
#continuation_prompt = ' ' # Font Awesome, Ellipsis H, F141
#continuation_prompt = ' ' # Font Awesome, Forward, F04E
#continuation_prompt = ' ' # Font Awesome, Greater Than, EDFB
#continuation_prompt = ' ' # Font Awesome, Greater Than Equal, EDFC
#continuation_prompt = ' ' # Font Awesome, Hand O Right, F0A4
#continuation_prompt = ' ' # Font Awesome, Hand Point Right, F0A4
#continuation_prompt = ' ' # Font Awesome, Right From Bracket, F2F5
#continuation_prompt = ' ' # Font Awesome, Sign Out, F08B
#continuation_prompt = ' ' # Font Awesome Extension, Bigger, E285
#continuation_prompt = ' ' # Font Awesome Extension, Equal Bigger, E27A
#continuation_prompt = '󰞘 ' # Material Design Icons, Arrow Expand Right, F0798
#continuation_prompt = '󰁔 ' # Material Design Icons, Arrow Right, F0054
#continuation_prompt = '󰜴 ' # Material Design Icons, Arrow Right Bold, F0734
#continuation_prompt = '󰜵 ' # Material Design Icons, Arrow Right Bold Box, F0735
#continuation_prompt = '󰜶 ' # Material Design Icons, Arrow Right Bold Box Outline, F0736
#continuation_prompt = '󰁖 ' # Material Design Icons, Arrow Right Bold Circle, F0056
#continuation_prompt = '󰁗 ' # Material Design Icons, Arrow Right Bold Circle Outline, F0057
#continuation_prompt = '󰧂 ' # Material Design Icons, Arrow Right Bold Outline, F09C2
#continuation_prompt = '󱞩 ' # Material Design Icons, Arrow Right Bottom, F17A9
#continuation_prompt = '󱞪 ' # Material Design Icons, Arrow Right Bottom Bold, F17AA
#continuation_prompt = '󰛂 ' # Material Design Icons, Arrow Right Box, F06C2
#continuation_prompt = '󰳟 ' # Material Design Icons, Arrow Right Circle, F0CDF
#continuation_prompt = '󰳠 ' # Material Design Icons, Arrow Right Circle Outline, F0CE0
#continuation_prompt = '󰁙 ' # Material Design Icons, Arrow Right Drop Circle, F0059
#continuation_prompt = '󰁚 ' # Material Design Icons, Arrow Right Drop Circle Outline, F005A
#continuation_prompt = '󰁕 ' # Material Design Icons, Arrow Right Thick, F0055
#continuation_prompt = '󱦰 ' # Material Design Icons, Arrow Right Thin, F19B0
#continuation_prompt = '󱖘 ' # Material Design Icons, Arrow Right Thin Circle Outline, F1598
#continuation_prompt = '󱞵 ' # Material Design Icons, Arrow U Right Bottom, F17B5
#continuation_prompt = '󱞶 ' # Material Design Icons, Arrow U Right Bottom, F17B6
#continuation_prompt = '󰄾 ' # Material Design Icons, Chevron Double Right, F013E
#continuation_prompt = '󰅂 ' # Material Design Icons, Chevron Right, F0142
#continuation_prompt = '󰧚 ' # Material Design Icons, Chevron Right Box, F09DA
#continuation_prompt = '󰧛 ' # Material Design Icons, Chevron Right Box Outline, F09DB
#continuation_prompt = '󰬪 ' # Material Design Icons, Chevron Right Circle, F0B2A
#continuation_prompt = '󰬫 ' # Material Design Icons, Chevron Right Circle Outline, F0B2B
#continuation_prompt = '󰶻 ' # Material Design Icons, Chevron Triple Right, F0DBB
#continuation_prompt = '󰊍 ' # Material Design Icons, Forward, F028D
#continuation_prompt = '󰵵 ' # Material Design Icons, Forwardburger, F0D75
#continuation_prompt = '󰣡 ' # Material Design Icons, Gate And, F08E1
#continuation_prompt = '󰥭 ' # Material Design Icons, Greater Than, F096D
#continuation_prompt = '󰋇 ' # Material Design Icons, Hand Pointing Right, F02C7
#continuation_prompt = '󰿅 ' # Material Design Icons, Location Exit, F0FC5
#continuation_prompt = '󰍃 ' # Material Design Icons, Logout, F0342
#continuation_prompt = '󰗽 ' # Material Design Icons, Logout Variant, F05FD
#continuation_prompt = '󰽝 ' # Material Design Icons, Middleware, F0F5D
#continuation_prompt = '󰽞 ' # Material Design Icons, Middleware Outline, F0F5E
#continuation_prompt = '󰮺 ' # Material Design Icons, Pan Right, F0BBA
#continuation_prompt = '󰐊 ' # Material Design Icons, Play, F040A
#continuation_prompt = '󱉺 ' # Material Design Icons, Play Box, F127A
#continuation_prompt = '󰐋 ' # Material Design Icons, Play Box Outline, F040B
#continuation_prompt = '󰐌 ' # Material Design Icons, Play Circle, F040C
#continuation_prompt = '󰐍 ' # Material Design Icons, Play Circle Outline, F040D
#continuation_prompt = '󰼛 ' # Material Design Icons, Play Outline, F0F1B
#continuation_prompt = '󰚺 ' # Material Design Icons, Plex, F06BA
#continuation_prompt = '󰐕 ' # Material Design Icons, Plus, F0415
#continuation_prompt = '󰐖 ' # Material Design Icons, Plus Box, F0416
#continuation_prompt = '󰜄 ' # Material Design Icons, Plus Box Outline, F0704
#continuation_prompt = '󰐗 ' # Material Design Icons, Plus Circle, F0417
#continuation_prompt = '󰐙 ' # Material Design Icons, Plus Circle Outline, F0419
#continuation_prompt = '󰜅 ' # Material Design Icons, Plus Outline, F0705
#continuation_prompt = '󱇬 ' # Material Design Icons, Plus Thick, F11EC
#continuation_prompt = '󰳀 ' # Material Design Icons, Radius, F0CC0
#continuation_prompt = '󰳁 ' # Material Design Icons, Radius Outline, F0CC1
#continuation_prompt = '󰑃 ' # Material Design Icons, Ray Start Arrow, F0443
#continuation_prompt = '󰑎 ' # Material Design Icons, Redo, F044E
#continuation_prompt = '󱜧 ' # Material Design Icons, Script Text Play, F1727
#continuation_prompt = '󱜨 ' # Material Design Icons, Script Text Play Outline, F1728
#continuation_prompt = '󰒊 ' # Material Design Icons, Send, F048A
#continuation_prompt = '󰷸 ' # Material Design Icons, Send Circle, F0DF8
#continuation_prompt = '󰷹 ' # Material Design Icons, Send Circle, F0DF9
#continuation_prompt = '󱅥 ' # Material Design Icons, Send Outline, F1165
#continuation_prompt = '󱓡 ' # Material Design Icons, Set Split, F14E1
#continuation_prompt = '󰒞 ' # Material Design Icons, Shuffle Disabled, F049E
#continuation_prompt = '󰘍 ' # Material Design Icons, Subdirectory Arrow Right, F060D
#continuation_prompt = '󰔰 ' # Material Design Icons, Transfer Right, F0530
#continuation_prompt = '󰔴 ' # Material Design Icons, Trending Neutral, F0534
#continuation_prompt = '󰔾 ' # Material Design Icons, Truck Delivery, F053E
#continuation_prompt = '󱊛 ' # Material Design Icons, Truck Delivery Outline, F129B
#continuation_prompt = '󱡚 ' # Material Design Icons, Waves Arrow Right, F185A
#continuation_prompt = '󰯟 ' # Material Design Icons, Wrap Disabled, F0BDF
#continuation_prompt = ' ' # Octicons, Arrow Right, F432
#continuation_prompt = ' ' # Octicons, Chevron Right, F460
#continuation_prompt = ' ' # Octicons, Diff Renamed, F45A
#continuation_prompt = ' ' # Octicons, Iterations, F4EA
#continuation_prompt = ' ' # Octicons, Package Dependents, F4F9
#continuation_prompt = ' ' # Octicons, Paper Airplane, F4FA
#continuation_prompt = ' ' # Octicons, Play, F500
#continuation_prompt = ' ' # Octicons, Plus, F44D
#continuation_prompt = ' ' # Octicons, Plus Circle, F501
#continuation_prompt = ' ' # Octicons, Sign Out, F426
#continuation_prompt = ' ' # Weather Icons, Direction Right, E349
#continuation_prompt = ' ' # Weather Icons, Wind West, E354


[fill]
symbol = ' '

[os]
disabled = false
style = "bg:color_orange fg:color_fg0"

[username]
show_always = true
style_user = "bg:color_orange fg:color_fg0"
style_root = "bg:color_orange fg:color_fg0"
format = '[ $user ]($style)'

[directory]
style = "fg:color_fg0 bg:color_yellow"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Development" = "󰲋 "
"Movies" = "󰟞"

[git_branch]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_aqua)]($style)'

[git_status]
style = "bg:color_aqua"
format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_aqua)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg1"
format = '[[  $time ](fg:color_fg0 bg:color_bg1)]($style)'

[jobs]
symbol = ' '
style = 'red'
number_threshold = 1
format = '[$symbol]($style)'

[cmd_duration]
min_time = 500
style = 'fg:gray'
format = '[$duration]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'

# I'm not using the shell's vim mode rn.
#vimcmd_symbol = '[](bold fg:color_green)'
#vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
#vimcmd_replace_symbol = '[](bold fg:color_purple)'
#vimcmd_visual_symbol = '[](bold fg:color_yellow)'

[shell]
disabled = false
bash_indicator = '󱆃'
zsh_indicator = '⚡'
powershell_indicator = ''
unknown_indicator = '⁇'
style = "bg:color_orange fg:color_fg0"
format = '[ $indicator]($style)'


[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""


[c]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[conda]
style = "bg:color_bg3"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:color_bg3)]($style)'

[docker_context]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'

[golang]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[haskell]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[java]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[kotlin]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[lua]
symbol = ' '
style = "bg:color_blue"

[nodejs]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[php]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[python]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[ruby]
style = "bg:color_blue"
symbol = ' '

[rust]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'


[palettes.nord]
black = '#2E3440'
gray = '#434C5E'
white='#D8DEE9'
red = '#BF616A'
orange = '#D08770'
yellow = '#EBCB8B'
green = '#A3BE8C'
teal = '#88C0D0'
blue = '#81A1C1'
purple = '#B48EAD'
dark_blue = '#5E81AC'

[palettes.onedark]
black='#2c323c'
gray='#828997'
white ='#abb2bf'
red='#e06c75'
orange='#be5046'
yellow='#e5c07b'
green='#98c379'
cyan='#56b6c2'
blue='#56b6c2'
purple='#c678dd'
dark_blue='#61afef'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'







#fun_glyph = ' ' # Codicons, Issues, EB0C
#fun_glyph = ' ' # Codicons, Record, EBA7
#fun_glyph = ' ' # Codicons, Record Small, EBFA
#fun_glyph = ' ' # Codicons, Sparkle, EC10
#fun_glyph = ' ' # Codicons, Star Full, EB59
#fun_glyph = ' ' # Custom, Scheme, E6B1
#fun_glyph = ' ' # Font Awesome, Bong, EE25
#fun_glyph = ' ' # Font Awesome, Brain, EE9C
#fun_glyph = ' ' # Font Awesome, Circle Dot, f192
#fun_glyph = ' ' # Font Awesome, Dot Circle O, f192
#fun_glyph = ' ' # Font Awesome, Drum, ee32
#fun_glyph = ' ' # Font Awesome, Hand Middle Finger, EF83
#fun_glyph = ' ' # Font Awesome, Jet Fighter, F0FB
#fun_glyph = ' ' # Font Awesome, Joint, EE5E
#fun_glyph = ' ' # Font Awesome, Plane, F072
#fun_glyph = ' ' # Font Awesome, Space Shuttle, F197
#fun_glyph = ' ' # Font Awesome, Terminal, F120
#fun_glyph = ' ' # Font Awesome, Triangle Exclamation, F071
#fun_glyph = ' ' # Font Awesome, Wand Sparkles, EF15
#fun_glyph = ' ' # Font Awesome Extension, Brain, E28C
#fun_glyph = ' ' # Font Awesome Extension, Gps, E248
#fun_glyph = '󰢚 ' # Material Design Icons, Alien, F089A
#fun_glyph = '󱃋 ' # Material Design Icons, Alien Outline, F10CB
#fun_glyph = '󰁨 ' # Material Design Icons, Auto Fix, F0068
#fun_glyph = '󰣈 ' # Material Design Icons, Axe, F08C8
#fun_glyph = '󱡂 ' # Material Design Icons, Axe Battle, F1842
#fun_glyph = '󰭟 ' # Material Design Icons, Bat, F0B5F
#fun_glyph = '󰄪 ' # Material Design Icons, Chart Line, F1213
#fun_glyph = '󰞷 ' # Material Design Icons, Console Line, F07B7
#fun_glyph = '󰙴 ' # Material Design Icons, Creation, F0674
#fun_glyph = '󰆣 ' # Material Design Icons, Crosshairs, F01A3
#fun_glyph = '󰆤 ' # Material Design Icons, Crosshairs Gps, F01A4
#fun_glyph = '󰬯 ' # Material Design Icons, Crystal Ball, F02BF
#fun_glyph = '󰈑 ' # Material Design Icons, Fast Forward, F0211
#fun_glyph = '󰛒 ' # Material Design Icons, Fast Forward Outline, F06D2
#fun_glyph = '󰊠 ' # Material Design Icons, Ghost, F02A0
#fun_glyph = '󱙝 ' # Material Design Icons, Ghost Outline, F165D
#fun_glyph = '󰊱 ' # Material Design Icons, Google Circles Communities, F02B1 # Nicholas Roerich Peace Symbol
#fun_glyph = '󰘧 ' # Material Design Icons, Lambda, F082D
#fun_glyph = '󰷚 ' # Material Design Icons, Mine, F0DDA
#fun_glyph = '󰽥 ' # Material Design Icons, Moon Waning Crescent, F0F65
#fun_glyph = '󰽧 ' # Material Design Icons, Moon Waxing Crescent, F0F67
#fun_glyph = '󱖲 ' # Material Design Icons, Motion, F15B2
#fun_glyph = '󱖳 ' # Material Design Icons, Motion Outline, F15B3
#fun_glyph = '󰟟 ' # Material Design Icons, Mushroom, F07DF
#fun_glyph = '󰟠 ' # Material Design Icons, Mushroom Outline, F07E0
#fun_glyph = '󰝴 ' # Material Design Icons, Ninja, F0774
#fun_glyph = '󰏅 ' # Material Design Icons, Odnoklassniki, F03C5
#fun_glyph = '󰮭 ' # Material Design Icons, One Up, F0BAD
#fun_glyph = '󰜃 ' # Material Design Icons, Pistol, F0703
#fun_glyph = '󱁘 ' # Material Design Icons, Robber, F1058
#fun_glyph = '󰓾 ' # Material Design Icons, Target, F04FE
#fun_glyph = ' ' # Material Design Icons, , 
#fun_glyph = ' ' # Octicons, Issue Opened, F41B
